"""Seed estático — popula MongoDB sem usar LLM.

Todas as lições estão embutidas neste arquivo.
Idempotente: usa upsert por (path_slug, order).

Uso:
    python seed_static.py           # todas as trilhas
    python seed_static.py python    # só Python
"""
import asyncio
import re
import sys
import uuid
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from motor.motor_asyncio import AsyncIOMotorClient
import os

ROOT = Path(__file__).parent
load_dotenv(ROOT / ".env")

client = AsyncIOMotorClient(os.environ["MONGO_URL"])
db = client[os.environ.get("DB_NAME", "codefuturo")]

# ---------------------------------------------------------------------------
# Metadados das trilhas
# ---------------------------------------------------------------------------

PATHS = [
    {"slug": "python-zero",  "name": "Python",      "language": "python",     "color": "#3776AB", "real_exec": True,  "desc": "A linguagem mais popular para iniciantes. Base sólida para IA, web, dados e automação."},
    {"slug": "javascript",   "name": "JavaScript",   "language": "javascript", "color": "#F7DF1E", "real_exec": True,  "desc": "A linguagem da web. Interatividade, frameworks modernos e Node.js."},
    {"slug": "html-css",     "name": "HTML & CSS",   "language": "html",       "color": "#E34F26", "real_exec": False, "desc": "A base da web. Aprenda a estruturar páginas e criar layouts modernos."},
    {"slug": "sql",          "name": "SQL",          "language": "sql",        "color": "#CC2927", "real_exec": False, "desc": "Linguagem para consultar e manipular bancos de dados relacionais."},
    {"slug": "typescript",   "name": "TypeScript",   "language": "typescript", "color": "#3178C6", "real_exec": False, "desc": "JavaScript com tipos. Essencial para projetos profissionais em escala."},
    {"slug": "java",         "name": "Java",         "language": "java",       "color": "#EA2D2E", "real_exec": False, "desc": "Orientação a objetos robusta. Usada em Android, empresas e backend."},
    {"slug": "cpp",          "name": "C++",          "language": "cpp",        "color": "#00599C", "real_exec": False, "desc": "Performance e controle total. Base de jogos, sistemas e engenharia."},
    {"slug": "go",           "name": "Go",           "language": "go",         "color": "#00ADD8", "real_exec": False, "desc": "Linguagem simples e poderosa do Google. Ideal para backend e DevOps."},
    {"slug": "ai-prompts",   "name": "AI Prompts",   "language": "prompts",    "color": "#A3E635", "real_exec": False, "desc": "Aprenda a conversar com IA. Engenharia de prompts para GPT, Claude e Gemini."},
]

# ---------------------------------------------------------------------------
# Lições por trilha
# Campos: title, chapter, order, instruction_pt, instruction_en, instruction_es,
#         starter_code, hint, tests: [{stdin, expected_stdout}]
# ---------------------------------------------------------------------------

LESSONS = {

# ── Python ──────────────────────────────────────────────────────────────────
"python-zero": [
  {
    "order": 1,
    "title": "Olá, Mundo!",
    "chapter": "Capítulo 1: Primeiros Passos",
    "instruction_pt": 'A função `print()` exibe texto na tela. O texto deve estar entre aspas DENTRO dos parênteses:\n\n  print("texto aqui")\n\nAspas duplas " ou aspas simples \' funcionam igualmente em Python. Complete o código ao lado para exibir exatamente: Olá, Mundo!',
    "instruction_en": 'The `print()` function displays text on screen. The text must be inside quotes WITHIN the parentheses:\n\n  print("text here")\n\nDouble " or single \' quotes both work in Python. Complete the code to display exactly: Olá, Mundo!',
    "instruction_es": 'La función `print()` muestra texto en pantalla. El texto debe estar entre comillas DENTRO de los paréntesis:\n\n  print("texto aquí")\n\nLas comillas dobles " y simples \' funcionan igual en Python. Completa el código para mostrar exactamente: Olá, Mundo!',
    "starter_code": '# print() exibe texto na tela\n# As aspas ficam DENTRO dos parênteses:\nprint("Olá, Mundo!")\n',
    "hint": 'O texto fica dentro do print(), entre aspas: print("Olá, Mundo!") — as aspas fazem parte do Python, não do texto exibido.',
    "tests": [{"stdin": "", "expected_stdout": "Olá, Mundo!"}],
  },
  {
    "order": 2,
    "title": "Variáveis",
    "chapter": "Capítulo 1: Primeiros Passos",
    "instruction_pt": "Variáveis guardam dados. Use `nome = valor` para criar uma variável. F-strings (f\"...\") permitem inserir variáveis dentro de texto usando `{variavel}`.",
    "instruction_en": "Variables store data. Use `name = value` to create a variable. F-strings allow inserting variables inside text using `{variable}`.",
    "instruction_es": "Las variables guardan datos. Usa `nombre = valor` para crear una variable. Las f-strings permiten insertar variables dentro del texto usando `{variable}`.",
    "starter_code": '# As variáveis abaixo estão fixas — não precisa alterar\nnome = "Ana"\nidade = 16\n# Imprima exatamente: Olá! Meu nome é Ana e tenho 16 anos.\nprint(f"Olá! Meu nome é {nome} e tenho {idade} anos.")\n',
    "hint": "Use f\"...\" com chaves ao redor das variáveis: f\"Olá! Meu nome é {nome}...\"",
    "tests": [{"stdin": "", "expected_stdout": "Olá! Meu nome é Ana e tenho 16 anos."}],
  },
  {
    "order": 3,
    "title": "Entrada do Usuário",
    "chapter": "Capítulo 1: Primeiros Passos",
    "instruction_pt": "`input()` lê o que o usuário digita e retorna uma string. Combine com `print()` para criar programas interativos. O teste passa 'Carlos' como entrada — seu programa deve responder com 'Bem-vindo, Carlos!'",
    "instruction_en": "`input()` reads what the user types and returns a string. The test passes 'Carlos' as input — your program should respond with 'Bem-vindo, Carlos!'",
    "instruction_es": "`input()` lee lo que el usuario escribe y devuelve un string. La prueba pasa 'Carlos' como entrada — tu programa debe responder con 'Bem-vindo, Carlos!'",
    "starter_code": '# Leia o nome do usuário e cumprimente-o\nnome = input()\n# Imprima: Bem-vindo, <nome>!\n# escreva aqui\n',
    "hint": "Use print(f\"Bem-vindo, {nome}!\") após ler o nome com input().",
    "tests": [{"stdin": "Carlos", "expected_stdout": "Bem-vindo, Carlos!"}],
  },
  {
    "order": 4,
    "title": "Condicionais",
    "chapter": "Capítulo 2: Lógica e Controle",
    "instruction_pt": "`if`, `elif` e `else` permitem que o programa tome decisões. O bloco indentado (4 espaços) após o `if` executa somente quando a condição é verdadeira.",
    "instruction_en": "`if`, `elif` and `else` allow the program to make decisions. The indented block after `if` runs only when the condition is true.",
    "instruction_es": "`if`, `elif` y `else` permiten que el programa tome decisiones. El bloque indentado después del `if` se ejecuta solo cuando la condición es verdadera.",
    "starter_code": 'numero = int(input())\n# Se > 0 imprima "positivo"\n# Se < 0 imprima "negativo"\n# Se == 0 imprima "zero"\n# escreva aqui\n',
    "hint": "Estrutura: if numero > 0: / print(\"positivo\") / elif numero < 0: / ... / else: / ...",
    "tests": [
      {"stdin": "7",  "expected_stdout": "positivo"},
      {"stdin": "-3", "expected_stdout": "negativo"},
      {"stdin": "0",  "expected_stdout": "zero"},
    ],
  },
  {
    "order": 5,
    "title": "Loops com for",
    "chapter": "Capítulo 2: Lógica e Controle",
    "instruction_pt": "`for` repete um bloco de código. `range(1, 6)` gera os números 1, 2, 3, 4, 5. Use `for i in range(...)` para iterar sobre sequências.",
    "instruction_en": "`for` repeats a block of code. `range(1, 6)` generates numbers 1, 2, 3, 4, 5. Use `for i in range(...)` to iterate over sequences.",
    "instruction_es": "`for` repite un bloque de código. `range(1, 6)` genera los números 1, 2, 3, 4, 5. Usa `for i in range(...)` para iterar sobre secuencias.",
    "starter_code": '# Imprima os números de 1 a 5, um por linha\n# escreva aqui\n',
    "hint": "Use: for i in range(1, 6): / print(i)",
    "tests": [{"stdin": "", "expected_stdout": "1\n2\n3\n4\n5"}],
  },
  {
    "order": 6,
    "title": "Funções",
    "chapter": "Capítulo 3: Funções e Estruturas",
    "instruction_pt": "Funções agrupam código reutilizável. `def nome(parametros):` define uma função e `return` devolve um resultado. Chame a função pelo nome para executá-la.",
    "instruction_en": "Functions group reusable code. `def name(parameters):` defines a function and `return` returns a result. Call the function by name to run it.",
    "instruction_es": "Las funciones agrupan código reutilizable. `def nombre(parámetros):` define una función y `return` devuelve un resultado.",
    "starter_code": '# Crie uma função que recebe dois números e retorna a soma\ndef somar(a, b):\n    # escreva aqui\n\nprint(somar(3, 7))\n',
    "hint": "Dentro da função, use: return a + b",
    "tests": [{"stdin": "", "expected_stdout": "10"}],
  },
  {
    "order": 7,
    "title": "Listas",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "Listas armazenam múltiplos valores em ordem. Use `lista[indice]` para acessar elementos (índice começa em 0). `.append()` adiciona ao final, `len()` retorna o tamanho.\n\nExemplo:\n  frutas = [\"maçã\", \"banana\", \"uva\"]\n  print(frutas[1])  # banana",
    "instruction_en": "Lists store multiple values in order. Use `list[index]` to access elements (index starts at 0). `.append()` adds to the end, `len()` returns the size.",
    "instruction_es": "Las listas almacenan múltiples valores en orden. Usa `lista[indice]` para acceder a elementos (el índice empieza en 0).",
    "starter_code": 'numeros = [10, 20, 30, 40, 50]\n# Imprima o terceiro elemento da lista\n# escreva aqui\n',
    "hint": "Índices começam em 0: numeros[0]=10, numeros[1]=20, numeros[2]=30...",
    "tests": [{"stdin": "", "expected_stdout": "30"}],
  },
  {
    "order": 8,
    "title": "Dicionários",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "Dicionários guardam pares `chave: valor`. Acesse valores pela chave: `dicionario[\"chave\"]`. Use `.keys()`, `.values()` e `.items()` para iterar.\n\nExemplo:\n  pessoa = {\"nome\": \"Ana\", \"idade\": 20}\n  print(pessoa[\"nome\"])  # Ana",
    "instruction_en": "Dictionaries store key-value pairs. Access values by key: `dict[\"key\"]`. Use `.keys()`, `.values()` and `.items()` to iterate.",
    "instruction_es": "Los diccionarios guardan pares clave-valor. Accede a los valores por la clave: `diccionario[\"clave\"]`.",
    "starter_code": 'aluno = {"nome": "Carlos", "nota": 9.5, "aprovado": True}\n# Imprima o nome do aluno\n# escreva aqui\n',
    "hint": "Use: print(aluno[\"nome\"])",
    "tests": [{"stdin": "", "expected_stdout": "Carlos"}],
  },
  {
    "order": 9,
    "title": "Métodos de String",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "Strings têm métodos embutidos muito úteis:\n- `.upper()` → MAIÚSCULAS\n- `.lower()` → minúsculas\n- `.strip()` → remove espaços\n- `.replace(a, b)` → substitui\n- `.count(x)` → conta ocorrências\n\nUse `.count()` para contar quantas vezes a letra 'a' aparece em 'banana'.",
    "instruction_en": "Strings have useful built-in methods: `.upper()`, `.lower()`, `.strip()`, `.replace()`, `.count()`. Use `.count()` to count occurrences.",
    "instruction_es": "Las strings tienen métodos integrados útiles. Usa `.count()` para contar cuántas veces aparece la letra 'a' en 'banana'.",
    "starter_code": 'palavra = "banana"\n# Conte quantas vezes a letra "a" aparece\n# escreva aqui\n',
    "hint": "Use: print(palavra.count(\"a\"))",
    "tests": [{"stdin": "", "expected_stdout": "3"}],
  },
  {
    "order": 10,
    "title": "Loop While",
    "chapter": "Capítulo 5: Controle Avançado",
    "instruction_pt": "`while` repete enquanto uma condição for verdadeira. Sempre garanta que a condição vai se tornar falsa para evitar loop infinito!\n\nExemplo:\n  i = 0\n  while i < 3:\n      print(i)\n      i += 1",
    "instruction_en": "`while` repeats while a condition is true. Always ensure the condition will eventually become false to avoid infinite loops!",
    "instruction_es": "`while` repite mientras una condición sea verdadera. ¡Siempre asegúrate de que la condición eventualmente se vuelva falsa!",
    "starter_code": '# Use while para imprimir os números de 1 a 5\ni = 1\n# escreva aqui (lembre de incrementar i)\n',
    "hint": "while i <= 5: / print(i) / i += 1",
    "tests": [{"stdin": "", "expected_stdout": "1\n2\n3\n4\n5"}],
  },
  {
    "order": 11,
    "title": "Compreensão de Lista",
    "chapter": "Capítulo 5: Controle Avançado",
    "instruction_pt": "List comprehension cria listas em uma linha só:\n\n  [expressão for item in iterável if condição]\n\nExemplo:\n  quadrados = [x**2 for x in range(5)]  # [0, 1, 4, 9, 16]",
    "instruction_en": "List comprehension creates lists in one line: `[expression for item in iterable if condition]`.",
    "instruction_es": "La comprensión de lista crea listas en una sola línea: `[expresión for item in iterable if condición]`.",
    "starter_code": '# Crie uma lista com os números pares de 1 a 10\n# Dica: x % 2 == 0 é verdadeiro quando x é par\npares = [x for x in range(1, 11) if x % 2 == 0]\nprint(pares)\n',
    "hint": "[x for x in range(1, 11) if x % 2 == 0]",
    "tests": [{"stdin": "", "expected_stdout": "[2, 4, 6, 8, 10]"}],
  },
  {
    "order": 12,
    "title": "Tratamento de Erros",
    "chapter": "Capítulo 5: Controle Avançado",
    "instruction_pt": "`try/except` captura erros e evita que o programa trave:\n\n  try:\n      # código que pode falhar\n  except TipoDoErro:\n      # o que fazer se falhar\n\nErros comuns: `ZeroDivisionError`, `ValueError`, `TypeError`.",
    "instruction_en": "`try/except` catches errors and prevents crashes. Common errors: `ZeroDivisionError`, `ValueError`, `TypeError`.",
    "instruction_es": "`try/except` captura errores y evita que el programa se bloquee.",
    "starter_code": '# Capture o erro de divisão por zero\ntry:\n    resultado = 10 / 0\nexcept ZeroDivisionError:\n    # escreva aqui o que imprimir\n',
    "hint": "print(\"Não é possível dividir por zero!\")",
    "tests": [{"stdin": "", "expected_stdout": "Não é possível dividir por zero!"}],
  },
  {
    "order": 13,
    "title": "Classes e Objetos",
    "chapter": "Capítulo 6: Orientação a Objetos",
    "instruction_pt": "Classes são moldes para criar objetos. `__init__` é o construtor — é chamado ao criar o objeto. `self` representa a instância.\n\n  class Carro:\n      def __init__(self, marca):\n          self.marca = marca",
    "instruction_en": "Classes are blueprints for creating objects. `__init__` is the constructor called when creating the object. `self` represents the instance.",
    "instruction_es": "Las clases son moldes para crear objetos. `__init__` es el constructor que se llama al crear el objeto.",
    "starter_code": 'class Carro:\n    def __init__(self, marca):\n        self.marca = marca\n\n    def apresentar(self):\n        return f"Este carro é um {self.marca}"\n\nmeu_carro = Carro("Toyota")\nprint(meu_carro.apresentar())\n',
    "hint": "O código já está quase completo — a classe Carro tem __init__ e apresentar(). Execute e veja o resultado!",
    "tests": [{"stdin": "", "expected_stdout": "Este carro é um Toyota"}],
  },
  {
    "order": 14,
    "title": "Herança",
    "chapter": "Capítulo 6: Orientação a Objetos",
    "instruction_pt": "Herança permite que uma classe filha herde atributos e métodos da classe pai. Use `super().__init__()` para chamar o construtor do pai.\n\n  class Animal:\n      def __init__(self, nome):\n          self.nome = nome\n\n  class Cachorro(Animal):\n      def latir(self):\n          return f\"{self.nome} diz: Au!\"",
    "instruction_en": "Inheritance allows a child class to inherit attributes and methods from a parent class. Use `super().__init__()` to call the parent constructor.",
    "instruction_es": "La herencia permite que una clase hija herede atributos y métodos de la clase padre.",
    "starter_code": 'class Animal:\n    def __init__(self, nome):\n        self.nome = nome\n\nclass Cachorro(Animal):\n    def latir(self):\n        return f"{self.nome} diz: Au!"\n\nrex = Cachorro("Rex")\nprint(rex.latir())\n',
    "hint": "O código já está pronto — execute para ver a herança em ação!",
    "tests": [{"stdin": "", "expected_stdout": "Rex diz: Au!"}],
  },
  {
    "order": 15,
    "title": "Lambda e Map",
    "chapter": "Capítulo 7: Funções Avançadas",
    "instruction_pt": "**Lambda** é uma função anônima de uma linha: `lambda x: x * 2`.\n**map()** aplica uma função a cada elemento de uma lista:\n\n  dobros = list(map(lambda x: x * 2, [1, 2, 3]))  # [2, 4, 6]",
    "instruction_en": "Lambda is an anonymous one-line function. `map()` applies a function to each list element.",
    "instruction_es": "Lambda es una función anónima de una línea. `map()` aplica una función a cada elemento de una lista.",
    "starter_code": 'numeros = [1, 2, 3, 4, 5]\n# Use map e lambda para triplicar cada número\ntriplicados = list(map(lambda x: x * 3, numeros))\nprint(triplicados)\n',
    "hint": "list(map(lambda x: x * 3, numeros))",
    "tests": [{"stdin": "", "expected_stdout": "[3, 6, 9, 12, 15]"}],
  },
  {
    "order": 16,
    "title": "Projeto: Fatorial",
    "chapter": "Capítulo 7: Funções Avançadas",
    "instruction_pt": "Combine tudo que aprendeu! O **fatorial** de n (escrito n!) é o produto de todos os inteiros de 1 até n.\n\n  5! = 5 × 4 × 3 × 2 × 1 = 120\n\nLeia um número com `input()`, calcule o fatorial com um loop `for` e imprima o resultado.",
    "instruction_en": "Combine everything learned! The factorial of n is the product of all integers from 1 to n. Read a number with `input()`, calculate the factorial with a `for` loop.",
    "instruction_es": "¡Combina todo lo aprendido! El factorial de n es el producto de todos los enteros del 1 al n.",
    "starter_code": 'n = int(input())\nresultado = 1\n# Use um loop for para calcular o fatorial\nfor i in range(1, n + 1):\n    # escreva aqui\n\nprint(resultado)\n',
    "hint": "Dentro do loop: resultado *= i (multiplica resultado pelo valor de i a cada iteração)",
    "tests": [
      {"stdin": "5",  "expected_stdout": "120"},
      {"stdin": "0",  "expected_stdout": "1"},
      {"stdin": "10", "expected_stdout": "3628800"},
    ],
  },
],

# ── JavaScript ───────────────────────────────────────────────────────────────
"javascript": [
  {
    "order": 1,
    "title": "console.log",
    "chapter": "Capítulo 1: Fundamentos",
    "instruction_pt": "`console.log()` exibe valores no terminal. É a forma mais básica de depurar e comunicar resultados em JavaScript.",
    "instruction_en": "`console.log()` displays values in the terminal. It's the most basic way to debug and communicate results in JavaScript.",
    "instruction_es": "`console.log()` muestra valores en el terminal. Es la forma más básica de depurar y comunicar resultados en JavaScript.",
    "starter_code": '// Exiba "Olá, JavaScript!" no console\n// escreva aqui\n',
    "hint": "Use: console.log(\"Olá, JavaScript!\")",
    "tests": [{"stdin": "", "expected_stdout": "Olá, JavaScript!"}],
  },
  {
    "order": 2,
    "title": "let e const",
    "chapter": "Capítulo 1: Fundamentos",
    "instruction_pt": "Use `const` para valores que não mudam e `let` para variáveis que podem ser reatribuídas. Template literals (crase) permitem interpolar variáveis com `${variavel}`.",
    "instruction_en": "Use `const` for values that don't change and `let` for variables that can be reassigned. Template literals (backtick) allow interpolating variables with `${variable}`.",
    "instruction_es": "Usa `const` para valores que no cambian y `let` para variables que pueden ser reasignadas.",
    "starter_code": 'const linguagem = "JavaScript";\nlet versao = 2024;\n// Exiba: Aprendendo JavaScript versão 2024\nconsole.log(`Aprendendo ${linguagem} versão ${versao}`);\n',
    "hint": "O código já está quase pronto — o console.log usa template literal corretamente.",
    "tests": [{"stdin": "", "expected_stdout": "Aprendendo JavaScript versão 2024"}],
  },
  {
    "order": 3,
    "title": "Funções",
    "chapter": "Capítulo 1: Fundamentos",
    "instruction_pt": "Funções em JS são declaradas com `function nome(params) { ... }`. Use `return` para devolver valores. Chame a função pelo nome seguido de parênteses.",
    "instruction_en": "Functions in JS are declared with `function name(params) { ... }`. Use `return` to return values. Call the function by name followed by parentheses.",
    "instruction_es": "Las funciones en JS se declaran con `function nombre(params) { ... }`. Usa `return` para devolver valores.",
    "starter_code": '// Complete a função que recebe um nome e retorna uma saudação\nfunction saudar(nome) {\n    // escreva aqui (return "Olá, " + nome + "!")\n}\nconsole.log(saudar("Mundo"));\n',
    "hint": "Dentro da função: return \"Olá, \" + nome + \"!\"",
    "tests": [{"stdin": "", "expected_stdout": "Olá, Mundo!"}],
  },
  {
    "order": 4,
    "title": "Arrays",
    "chapter": "Capítulo 2: Estruturas de Dados",
    "instruction_pt": "Arrays armazenam listas de valores. Use `array[indice]` para acessar elementos (começa no índice 0). `.length` retorna o tamanho do array.",
    "instruction_en": "Arrays store lists of values. Use `array[index]` to access elements (starts at index 0). `.length` returns the array size.",
    "instruction_es": "Los arrays almacenan listas de valores. Usa `array[indice]` para acceder a elementos (comienza en el índice 0).",
    "starter_code": 'const frutas = ["maçã", "banana", "laranja"];\n// Exiba o segundo elemento do array\n// escreva aqui\n',
    "hint": "Índices começam em 0: frutas[0] é \"maçã\", frutas[1] é \"banana\"",
    "tests": [{"stdin": "", "expected_stdout": "banana"}],
  },
  {
    "order": 5,
    "title": "Objetos",
    "chapter": "Capítulo 2: Estruturas de Dados",
    "instruction_pt": "Objetos armazenam pares `chave: valor`. Acesse propriedades com ponto `.` ou colchetes `[\"chave\"]`.\n\n  const carro = { marca: \"Toyota\", ano: 2024 };\n  console.log(carro.marca); // Toyota",
    "instruction_en": "Objects store key-value pairs. Access properties with dot `.` or brackets `[\"key\"]`.",
    "instruction_es": "Los objetos almacenan pares clave-valor. Accede con punto `.` o corchetes `[\"clave\"]`.",
    "starter_code": 'const produto = { nome: "Notebook", preco: 2999, disponivel: true };\n// Imprima o nome do produto\n// escreva aqui\n',
    "hint": "Use: console.log(produto.nome)",
    "tests": [{"stdin": "", "expected_stdout": "Notebook"}],
  },
  {
    "order": 6,
    "title": "Condicionais",
    "chapter": "Capítulo 2: Estruturas de Dados",
    "instruction_pt": "`if/else` permite tomar decisões. O operador ternário `condição ? valor1 : valor2` é uma versão compacta.\n\n  const idade = 20;\n  console.log(idade >= 18 ? \"adulto\" : \"menor\");",
    "instruction_en": "`if/else` allows decisions. The ternary `condition ? value1 : value2` is a compact version.",
    "instruction_es": "`if/else` permite tomar decisiones. El ternario `condición ? valor1 : valor2` es la versión compacta.",
    "starter_code": 'const temperatura = 35;\n// Se temperatura > 30, imprima "calor"\n// Senão, imprima "agradável"\n// Use if/else ou ternário\n// escreva aqui\n',
    "hint": "if (temperatura > 30) { console.log(\"calor\"); } else { console.log(\"agradável\"); }",
    "tests": [{"stdin": "", "expected_stdout": "calor"}],
  },
  {
    "order": 7,
    "title": "Loops",
    "chapter": "Capítulo 2: Estruturas de Dados",
    "instruction_pt": "Loops repetem código. `for` com índice, `for...of` para arrays, `while` para condições.\n\n  for (let i = 1; i <= 3; i++) { console.log(i); }\n  // ou: for (const item of array) { ... }",
    "instruction_en": "Loops repeat code. `for` with index, `for...of` for arrays, `while` for conditions.",
    "instruction_es": "Los loops repiten código. `for` con índice, `for...of` para arrays, `while` para condiciones.",
    "starter_code": 'const linguagens = ["Python", "JavaScript", "Go"];\n// Use for...of para imprimir cada linguagem\n// escreva aqui\n',
    "hint": "for (const lang of linguagens) { console.log(lang); }",
    "tests": [{"stdin": "", "expected_stdout": "Python\nJavaScript\nGo"}],
  },
  {
    "order": 8,
    "title": "Arrow Functions",
    "chapter": "Capítulo 3: Funções Modernas",
    "instruction_pt": "Arrow functions são uma forma concisa de escrever funções:\n\n  // Tradicional\n  function dobrar(n) { return n * 2; }\n\n  // Arrow\n  const dobrar = (n) => n * 2;\n\nCrie uma arrow function `area` que calcula largura × altura.",
    "instruction_en": "Arrow functions are a concise way to write functions: `const fn = (param) => expression`.",
    "instruction_es": "Las arrow functions son una forma concisa de escribir funciones: `const fn = (param) => expression`.",
    "starter_code": '// Crie uma arrow function "area" que recebe largura e altura\nconst area = (largura, altura) => largura * altura;\nconsole.log(area(6, 4));\n',
    "hint": "const area = (largura, altura) => largura * altura;",
    "tests": [{"stdin": "", "expected_stdout": "24"}],
  },
  {
    "order": 9,
    "title": "Map e Filter",
    "chapter": "Capítulo 3: Funções Modernas",
    "instruction_pt": "`.map()` transforma cada elemento. `.filter()` seleciona elementos por condição.\n\n  [1,2,3].map(x => x * 2)    // [2, 4, 6]\n  [1,2,3,4].filter(x => x > 2) // [3, 4]\n\nUse `.filter()` para contar quantos números do array são maiores que 10.",
    "instruction_en": "`.map()` transforms each element. `.filter()` selects elements by condition.",
    "instruction_es": "`.map()` transforma cada elemento. `.filter()` selecciona elementos por condición.",
    "starter_code": 'const numeros = [5, 12, 3, 18, 7, 25, 1];\n// Filtre os números maiores que 10 e imprima a quantidade\nconst maiores = numeros.filter(n => n > 10);\nconsole.log(maiores.length);\n',
    "hint": "filter retorna um novo array — use .length para contar os elementos",
    "tests": [{"stdin": "", "expected_stdout": "3"}],
  },
  {
    "order": 10,
    "title": "Destructuring",
    "chapter": "Capítulo 3: Funções Modernas",
    "instruction_pt": "Destructuring extrai valores de objetos e arrays em variáveis:\n\n  const { nome, cidade } = usuario;  // objeto\n  const [primeiro, segundo] = lista;  // array\n\nDesestruture o objeto abaixo e imprima nome e cidade.",
    "instruction_en": "Destructuring extracts values from objects and arrays into variables.",
    "instruction_es": "El destructuring extrae valores de objetos y arrays en variables.",
    "starter_code": 'const dev = { nome: "Ana", cidade: "São Paulo", nivel: "Sênior" };\n// Desestruture nome e cidade, depois imprima\nconst { nome, cidade } = dev;\nconsole.log(`${nome} mora em ${cidade}`);\n',
    "hint": "const { nome, cidade } = dev; depois: console.log(`${nome} mora em ${cidade}`)",
    "tests": [{"stdin": "", "expected_stdout": "Ana mora em São Paulo"}],
  },
  {
    "order": 11,
    "title": "Classes ES6",
    "chapter": "Capítulo 4: Orientação a Objetos",
    "instruction_pt": "Classes em JS usam `constructor` para inicializar e métodos dentro do corpo da classe.\n\n  class Animal {\n    constructor(nome) { this.nome = nome; }\n    falar() { return `${this.nome} faz som`; }\n  }",
    "instruction_en": "JS Classes use `constructor` to initialize and methods inside the class body.",
    "instruction_es": "Las clases JS usan `constructor` para inicializar y métodos dentro del cuerpo.",
    "starter_code": 'class Circulo {\n  constructor(raio) {\n    this.raio = raio;\n  }\n  area() {\n    // Área = PI × raio²  (use Math.PI e Math.pow ou **)\n    return Math.round(Math.PI * this.raio ** 2);\n  }\n}\nconst c = new Circulo(5);\nconsole.log(c.area());\n',
    "hint": "Math.round(Math.PI * 5 ** 2) = 79",
    "tests": [{"stdin": "", "expected_stdout": "79"}],
  },
  {
    "order": 12,
    "title": "Try/Catch",
    "chapter": "Capítulo 4: Orientação a Objetos",
    "instruction_pt": "`try/catch` captura erros e evita que o programa trave:\n\n  try {\n    // código arriscado\n  } catch (erro) {\n    console.log(erro.message);\n  }\n\nCapture o erro ao tentar fazer `JSON.parse` de texto inválido.",
    "instruction_en": "`try/catch` catches errors and prevents crashes. Use it to handle `JSON.parse` on invalid input.",
    "instruction_es": "`try/catch` captura errores y evita que el programa falle.",
    "starter_code": '// Tente parsear uma string inválida e capture o erro\ntry {\n  const dados = JSON.parse("isso não é json válido");\n} catch (e) {\n  console.log("Erro: JSON inválido");\n}\n',
    "hint": "O catch recebe o erro — dentro dele use console.log(\"Erro: JSON inválido\")",
    "tests": [{"stdin": "", "expected_stdout": "Erro: JSON inválido"}],
  },
],

# ── HTML & CSS ───────────────────────────────────────────────────────────────
"html-css": [
  {
    "order": 1,
    "title": "Título com h1",
    "chapter": "Capítulo 1: Estrutura HTML",
    "instruction_pt": "HTML usa tags para estruturar conteúdo. `<h1>` cria um título principal. Tags HTML seguem o padrão `<tag>conteúdo</tag>`. Escreva a tag que exibe o título 'Olá, Web!'",
    "instruction_en": "HTML uses tags to structure content. `<h1>` creates a main heading. Write the tag that displays the heading 'Olá, Web!'",
    "instruction_es": "HTML usa etiquetas para estructurar contenido. `<h1>` crea un título principal. Escribe la etiqueta que muestra el título 'Olá, Web!'",
    "starter_code": '<!DOCTYPE html>\n<html>\n  <body>\n    <!-- Adicione um título h1 com o texto: Olá, Web! -->\n    <!-- escreva aqui -->\n  </body>\n</html>\n',
    "hint": "Estrutura: <h1>texto aqui</h1>",
    "tests": [{"stdin": "", "expected_stdout": "<h1>Olá, Web!</h1>"}],
  },
  {
    "order": 2,
    "title": "Parágrafos",
    "chapter": "Capítulo 1: Estrutura HTML",
    "instruction_pt": "`<p>` cria parágrafos de texto. É a tag mais usada para conteúdo textual em páginas web. Escreva o parágrafo com o texto exato solicitado.",
    "instruction_en": "`<p>` creates text paragraphs. It's the most used tag for textual content on web pages.",
    "instruction_es": "`<p>` crea párrafos de texto. Es la etiqueta más usada para contenido textual en páginas web.",
    "starter_code": '<body>\n  <h1>Meu Site</h1>\n  <!-- Adicione um parágrafo com: Bem-vindo ao HTML! -->\n  <!-- escreva aqui -->\n</body>\n',
    "hint": "Use <p>texto aqui</p>",
    "tests": [{"stdin": "", "expected_stdout": "<p>Bem-vindo ao HTML!</p>"}],
  },
  {
    "order": 3,
    "title": "Links",
    "chapter": "Capítulo 1: Estrutura HTML",
    "instruction_pt": "`<a href=\"url\">texto</a>` cria links clicáveis. O atributo `href` define o destino. Escreva o link completo que aponta para https://codefuturo.com.br com o texto 'Acessar'. Aspas simples ' ou duplas \" funcionam igualmente.",
    "instruction_en": "`<a href=\"url\">text</a>` creates clickable links. The `href` attribute defines the destination. Single ' or double \" quotes both work.",
    "instruction_es": "`<a href=\"url\">texto</a>` crea enlaces clicables. El atributo `href` define el destino. Las comillas simples ' y dobles \" funcionan igual.",
    "starter_code": '<!-- Crie um link para https://codefuturo.com.br com o texto "Acessar" -->\n<!-- escreva aqui -->\n',
    "hint": "Estrutura: <a href=\"https://...\">texto</a> — aspas simples ou duplas são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": '<a href="https://codefuturo.com.br">Acessar</a>'}],
  },
  {
    "order": 4,
    "title": "Cor com CSS",
    "chapter": "Capítulo 2: Estilo com CSS",
    "instruction_pt": "CSS estiliza o HTML. A propriedade `color` define a cor do texto. Escreva apenas a declaração CSS que deixa o texto azul.",
    "instruction_en": "CSS styles HTML. The `color` property defines text color. Write only the CSS declaration that makes text blue.",
    "instruction_es": "CSS da estilo al HTML. La propiedad `color` define el color del texto. Escribe solo la declaración CSS que hace el texto azul.",
    "starter_code": '<style>\n  h1 {\n    /* Deixe o texto azul */\n    /* escreva aqui */\n  }\n</style>\n',
    "hint": "Propriedade: color: blue;",
    "tests": [{"stdin": "", "expected_stdout": "color: blue;"}],
  },
  {
    "order": 5,
    "title": "Imagem",
    "chapter": "Capítulo 1: Estrutura HTML",
    "instruction_pt": "`<img>` insere imagens. Atributos obrigatórios: `src` (caminho) e `alt` (descrição para acessibilidade). É uma tag auto-fechante — não precisa de `</img>`.\n\n  <img src=\"foto.jpg\" alt=\"Minha foto\">",
    "instruction_en": "`<img>` inserts images. Required attributes: `src` (path) and `alt` (accessibility description). It's self-closing.",
    "instruction_es": "`<img>` inserta imágenes. Atributos requeridos: `src` y `alt`. Es una etiqueta auto-cerrante.",
    "starter_code": '<!-- Adicione uma imagem com src="logo.png" e alt="Logo CodeFuturo" -->\n<!-- escreva aqui -->\n',
    "hint": "Estrutura: <img src=\"logo.png\" alt=\"Logo CodeFuturo\">",
    "tests": [{"stdin": "", "expected_stdout": '<img src="logo.png" alt="Logo CodeFuturo">'}],
  },
  {
    "order": 6,
    "title": "Listas",
    "chapter": "Capítulo 1: Estrutura HTML",
    "instruction_pt": "`<ul>` cria lista não ordenada (com bolinhas). `<ol>` cria lista ordenada (numerada). Cada item usa `<li>`.\n\n  <ul>\n    <li>Python</li>\n    <li>JavaScript</li>\n  </ul>",
    "instruction_en": "`<ul>` creates unordered (bulleted) lists. `<ol>` creates ordered (numbered) lists. Each item uses `<li>`.",
    "instruction_es": "`<ul>` crea listas no ordenadas. `<ol>` crea listas ordenadas. Cada elemento usa `<li>`.",
    "starter_code": '<!-- Crie uma lista não ordenada com 3 linguagens: Python, JavaScript, Go -->\n<!-- escreva aqui -->\n',
    "hint": "<ul><li>Python</li><li>JavaScript</li><li>Go</li></ul>",
    "tests": [{"stdin": "", "expected_stdout": "<li>Python</li>"}],
  },
  {
    "order": 7,
    "title": "Tabela",
    "chapter": "Capítulo 2: Conteúdo Estruturado",
    "instruction_pt": "Tabelas organizam dados em linhas e colunas:\n- `<table>` → container\n- `<tr>` → linha\n- `<th>` → cabeçalho\n- `<td>` → célula de dados\n\nCrie uma tabela com cabeçalhos Nome e Idade.",
    "instruction_en": "Tables organize data in rows and columns: `<table>`, `<tr>`, `<th>`, `<td>`.",
    "instruction_es": "Las tablas organizan datos en filas y columnas: `<table>`, `<tr>`, `<th>`, `<td>`.",
    "starter_code": '<!-- Crie uma tabela com cabeçalhos "Nome" e "Idade" -->\n<table>\n  <tr>\n    <!-- escreva os cabeçalhos aqui -->\n  </tr>\n</table>\n',
    "hint": "<th>Nome</th><th>Idade</th>",
    "tests": [{"stdin": "", "expected_stdout": "<th>Nome</th>"}],
  },
  {
    "order": 8,
    "title": "Formulário",
    "chapter": "Capítulo 2: Conteúdo Estruturado",
    "instruction_pt": "`<form>` agrupa campos de entrada. `<input>` recebe dados do usuário. Atributos importantes: `type` (text, email, password, submit) e `name`.\n\n  <input type=\"email\" name=\"email\" placeholder=\"seu@email.com\">",
    "instruction_en": "`<form>` groups input fields. `<input>` receives user data. Key attributes: `type` and `name`.",
    "instruction_es": "`<form>` agrupa campos de entrada. `<input>` recibe datos del usuario.",
    "starter_code": '<form>\n  <!-- Adicione um input do tipo "text" com name="usuario" -->\n  <!-- escreva aqui -->\n  <button type="submit">Enviar</button>\n</form>\n',
    "hint": "<input type=\"text\" name=\"usuario\">",
    "tests": [{"stdin": "", "expected_stdout": '<input type="text" name="usuario">'}],
  },
  {
    "order": 9,
    "title": "Classes CSS",
    "chapter": "Capítulo 3: Estilo com CSS",
    "instruction_pt": "Classes CSS permitem estilizar elementos específicos. Defina com `.nome-da-classe { }` e aplique no HTML com `class=\"nome\"`.\n\n  /* CSS */\n  .destaque { color: red; }\n\n  <!-- HTML -->\n  <p class=\"destaque\">Texto</p>",
    "instruction_en": "CSS classes style specific elements. Define with `.class-name { }` and apply with `class=\"name\"`.",
    "instruction_es": "Las clases CSS permiten estilizar elementos específicos. Define con `.nombre` y aplica con `class=\"nombre\"`.",
    "starter_code": '<style>\n  /* Crie uma classe "destaque" com color: orange */\n  /* escreva aqui */\n</style>\n<p class="destaque">Texto importante</p>\n',
    "hint": ".destaque { color: orange; }",
    "tests": [{"stdin": "", "expected_stdout": ".destaque"}],
  },
  {
    "order": 10,
    "title": "Tipografia CSS",
    "chapter": "Capítulo 3: Estilo com CSS",
    "instruction_pt": "CSS controla tipografia com:\n- `font-size: 24px` → tamanho\n- `font-weight: bold` → negrito\n- `font-family: Arial` → família\n- `text-align: center` → alinhamento\n\nEstilize o h1 com fonte de 32px e centralizado.",
    "instruction_en": "CSS controls typography: `font-size`, `font-weight`, `font-family`, `text-align`.",
    "instruction_es": "CSS controla la tipografía: `font-size`, `font-weight`, `font-family`, `text-align`.",
    "starter_code": '<style>\n  h1 {\n    /* Tamanho 32px e centralizado */\n    /* escreva aqui */\n  }\n</style>\n<h1>Título</h1>\n',
    "hint": "font-size: 32px; text-align: center;",
    "tests": [{"stdin": "", "expected_stdout": "font-size: 32px;"}],
  },
  {
    "order": 11,
    "title": "Flexbox",
    "chapter": "Capítulo 4: Layout Moderno",
    "instruction_pt": "Flexbox é o sistema de layout mais usado no CSS moderno. `display: flex` ativa o flex container. Use `justify-content` para alinhar horizontalmente e `align-items` verticalmente.\n\n  .container {\n    display: flex;\n    justify-content: center;\n  }",
    "instruction_en": "Flexbox is the most used layout system. `display: flex` activates the flex container.",
    "instruction_es": "Flexbox es el sistema de layout más usado en CSS moderno.",
    "starter_code": '<style>\n  .container {\n    /* Ative flexbox e centralize horizontalmente */\n    /* escreva aqui */\n  }\n</style>\n<div class="container">\n  <p>Item 1</p><p>Item 2</p><p>Item 3</p>\n</div>\n',
    "hint": "display: flex; justify-content: center;",
    "tests": [{"stdin": "", "expected_stdout": "display: flex;"}],
  },
  {
    "order": 12,
    "title": "Box Model",
    "chapter": "Capítulo 4: Layout Moderno",
    "instruction_pt": "Todo elemento HTML é uma caixa com 4 camadas:\n- **content** → conteúdo\n- **padding** → espaço interno\n- **border** → borda\n- **margin** → espaço externo\n\nCentralize um div adicionando `margin: 0 auto` e `width: 400px`.",
    "instruction_en": "Every HTML element is a box with content, padding, border, and margin.",
    "instruction_es": "Todo elemento HTML es una caja con content, padding, border y margin.",
    "starter_code": '<style>\n  .caixa {\n    width: 400px;\n    background: lightblue;\n    /* Centralize horizontalmente com margin */\n    /* escreva aqui */\n  }\n</style>\n<div class="caixa">Conteúdo centralizado</div>\n',
    "hint": "margin: 0 auto;",
    "tests": [{"stdin": "", "expected_stdout": "margin: 0 auto;"}],
  },
],

# ── SQL ──────────────────────────────────────────────────────────────────────
"sql": [
  {
    "order": 1,
    "title": "SELECT básico",
    "chapter": "Capítulo 1: Consultando Dados",
    "instruction_pt": "`SELECT` recupera dados de uma tabela. `SELECT * FROM tabela` retorna todas as colunas. Escreva a query completa que seleciona todos os dados da tabela 'usuarios'.",
    "instruction_en": "`SELECT` retrieves data from a table. `SELECT * FROM table` returns all columns.",
    "instruction_es": "`SELECT` recupera datos de una tabla. `SELECT * FROM tabla` devuelve todas las columnas.",
    "starter_code": '-- Selecione todos os dados da tabela "usuarios"\n-- escreva aqui\n',
    "hint": "SELECT * FROM nome_da_tabela;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT * FROM usuarios;"}],
  },
  {
    "order": 2,
    "title": "Filtrando com WHERE",
    "chapter": "Capítulo 1: Consultando Dados",
    "instruction_pt": "`WHERE` filtra as linhas retornadas. Escreva a query que seleciona todos os usuários cuja idade é maior que 18.",
    "instruction_en": "`WHERE` filters returned rows. Write the query that selects all users whose age is greater than 18.",
    "instruction_es": "`WHERE` filtra las filas devueltas. Escribe la consulta que selecciona todos los usuarios con edad mayor a 18.",
    "starter_code": '-- Selecione todos os usuários com idade > 18\n-- escreva aqui\n',
    "hint": "SELECT * FROM tabela WHERE coluna > valor;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT * FROM usuarios WHERE idade > 18;"}],
  },
  {
    "order": 3,
    "title": "Inserindo dados",
    "chapter": "Capítulo 2: Manipulando Dados",
    "instruction_pt": "`INSERT INTO` adiciona novos registros. Escreva o comando que insere um usuário com nome 'Maria' e email 'maria@email.com' na tabela 'usuarios'.",
    "instruction_en": "`INSERT INTO` adds new records. Write the command that inserts a user with name 'Maria' and email 'maria@email.com'.",
    "instruction_es": "`INSERT INTO` agrega nuevos registros. Escribe el comando que inserta un usuario con nombre 'Maria' y email 'maria@email.com'.",
    "starter_code": "-- Insira um usuário com nome 'Maria' e email 'maria@email.com'\n-- escreva aqui\n",
    "hint": "INSERT INTO tabela (coluna1, coluna2) VALUES ('valor1', 'valor2'); — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": "INSERT INTO usuarios (nome, email) VALUES ('Maria', 'maria@email.com');"}],
  },
  {
    "order": 4,
    "title": "Atualizando dados",
    "chapter": "Capítulo 2: Manipulando Dados",
    "instruction_pt": "`UPDATE ... SET ... WHERE` atualiza registros existentes. Sempre use `WHERE` para evitar alterar todos os registros. Escreva o comando que atualiza o email do usuário com id=1.",
    "instruction_en": "`UPDATE ... SET ... WHERE` updates existing records. Always use `WHERE` to avoid changing all records.",
    "instruction_es": "`UPDATE ... SET ... WHERE` actualiza registros existentes. Siempre usa `WHERE` para evitar cambiar todos los registros.",
    "starter_code": "-- Atualize o email para 'novo@email.com' do usuário com id = 1\n-- escreva aqui\n",
    "hint": "UPDATE tabela SET coluna = 'valor' WHERE id = 1; — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": "UPDATE usuarios SET email = 'novo@email.com' WHERE id = 1;"}],
  },
  {
    "order": 5,
    "title": "DELETE",
    "chapter": "Capítulo 2: Manipulando Dados",
    "instruction_pt": "`DELETE FROM` remove registros. **Sempre use `WHERE`** para evitar apagar tudo!\n\n  DELETE FROM tabela WHERE condição;\n\nEscreva o comando que remove o usuário com id = 5.",
    "instruction_en": "`DELETE FROM` removes records. Always use `WHERE` to avoid deleting everything!",
    "instruction_es": "`DELETE FROM` elimina registros. ¡Siempre usa `WHERE` para evitar borrar todo!",
    "starter_code": "-- Remova o usuário com id = 5 da tabela usuarios\n-- escreva aqui\n",
    "hint": "DELETE FROM tabela WHERE coluna = valor;",
    "tests": [{"stdin": "", "expected_stdout": "DELETE FROM usuarios WHERE id = 5;"}],
  },
  {
    "order": 6,
    "title": "ORDER BY",
    "chapter": "Capítulo 3: Consultando com Estilo",
    "instruction_pt": "`ORDER BY` ordena os resultados. Use `ASC` (crescente, padrão) ou `DESC` (decrescente).\n\n  SELECT * FROM produtos ORDER BY preco DESC;\n\nEscreva a query que lista todos os usuários ordenados por nome em ordem crescente.",
    "instruction_en": "`ORDER BY` sorts results. Use `ASC` (ascending, default) or `DESC` (descending).",
    "instruction_es": "`ORDER BY` ordena los resultados. Usa `ASC` (ascendente) o `DESC` (descendente).",
    "starter_code": "-- Liste todos os usuários ordenados pelo nome (A-Z)\n-- escreva aqui\n",
    "hint": "SELECT * FROM usuarios ORDER BY nome ASC;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT * FROM usuarios ORDER BY nome ASC;"}],
  },
  {
    "order": 7,
    "title": "LIMIT",
    "chapter": "Capítulo 3: Consultando com Estilo",
    "instruction_pt": "`LIMIT` restringe o número de linhas retornadas. Muito útil para paginação.\n\n  SELECT * FROM tabela LIMIT 10;\n\nEscreva a query que retorna os 3 primeiros produtos da tabela `produtos`.",
    "instruction_en": "`LIMIT` restricts the number of returned rows. Very useful for pagination.",
    "instruction_es": "`LIMIT` restringe el número de filas devueltas. Muy útil para paginación.",
    "starter_code": "-- Retorne apenas os 3 primeiros produtos\n-- escreva aqui\n",
    "hint": "SELECT * FROM produtos LIMIT 3;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT * FROM produtos LIMIT 3;"}],
  },
  {
    "order": 8,
    "title": "Funções de Agregação",
    "chapter": "Capítulo 3: Consultando com Estilo",
    "instruction_pt": "Funções de agregação calculam valores sobre múltiplas linhas:\n- `COUNT(*)` → conta linhas\n- `SUM(coluna)` → soma\n- `AVG(coluna)` → média\n- `MAX/MIN` → máximo/mínimo\n\nEscreva a query que conta o total de usuários.",
    "instruction_en": "Aggregate functions calculate values over multiple rows: COUNT, SUM, AVG, MAX, MIN.",
    "instruction_es": "Las funciones de agregación calculan valores sobre múltiples filas: COUNT, SUM, AVG, MAX, MIN.",
    "starter_code": "-- Conte o número total de usuários na tabela usuarios\n-- escreva aqui\n",
    "hint": "SELECT COUNT(*) FROM usuarios;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT COUNT(*) FROM usuarios;"}],
  },
  {
    "order": 9,
    "title": "GROUP BY",
    "chapter": "Capítulo 3: Consultando com Estilo",
    "instruction_pt": "`GROUP BY` agrupa linhas com o mesmo valor. Sempre usado com funções de agregação.\n\n  SELECT cidade, COUNT(*) FROM clientes GROUP BY cidade;\n\nEscreva a query que mostra quantos usuários existem por cidade.",
    "instruction_en": "`GROUP BY` groups rows with the same value. Always used with aggregate functions.",
    "instruction_es": "`GROUP BY` agrupa filas con el mismo valor. Siempre se usa con funciones de agregación.",
    "starter_code": "-- Mostre quantos usuários existem em cada cidade\n-- escreva aqui\n",
    "hint": "SELECT cidade, COUNT(*) FROM usuarios GROUP BY cidade;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT cidade, COUNT(*) FROM usuarios GROUP BY cidade;"}],
  },
  {
    "order": 10,
    "title": "INNER JOIN",
    "chapter": "Capítulo 4: Relacionamentos",
    "instruction_pt": "`JOIN` combina linhas de duas tabelas com base em uma coluna relacionada.\n`INNER JOIN` retorna apenas as linhas com correspondência em ambas.\n\n  SELECT u.nome, p.produto\n  FROM usuarios u\n  INNER JOIN pedidos p ON u.id = p.usuario_id;\n\nEscreva essa query exatamente.",
    "instruction_en": "`INNER JOIN` combines rows from two tables based on a related column, returning only matching rows.",
    "instruction_es": "`INNER JOIN` combina filas de dos tablas basándose en una columna relacionada.",
    "starter_code": "-- Una usuarios com pedidos pelo id do usuário\n-- Selecione u.nome e p.produto\n-- escreva aqui\n",
    "hint": "SELECT u.nome, p.produto FROM usuarios u INNER JOIN pedidos p ON u.id = p.usuario_id;",
    "tests": [{"stdin": "", "expected_stdout": "SELECT u.nome, p.produto FROM usuarios u INNER JOIN pedidos p ON u.id = p.usuario_id;"}],
  },
  {
    "order": 11,
    "title": "CREATE TABLE",
    "chapter": "Capítulo 4: Relacionamentos",
    "instruction_pt": "`CREATE TABLE` cria uma nova tabela. Defina as colunas com nome e tipo:\n- `INT` → inteiro\n- `VARCHAR(n)` → texto até n caracteres\n- `DECIMAL(10,2)` → número decimal\n- `PRIMARY KEY` → chave primária\n\nCrie a tabela `produtos` com id (INT), nome (VARCHAR 100) e preco (DECIMAL 10,2).",
    "instruction_en": "`CREATE TABLE` creates a new table. Define columns with name and type.",
    "instruction_es": "`CREATE TABLE` crea una nueva tabla. Define las columnas con nombre y tipo.",
    "starter_code": "-- Crie a tabela produtos com id (INT), nome (VARCHAR(100)) e preco (DECIMAL(10,2))\n-- escreva aqui\n",
    "hint": "CREATE TABLE produtos (id INT, nome VARCHAR(100), preco DECIMAL(10,2));",
    "tests": [{"stdin": "", "expected_stdout": "CREATE TABLE produtos (id INT, nome VARCHAR(100), preco DECIMAL(10,2));"}],
  },
  {
    "order": 12,
    "title": "ALTER TABLE",
    "chapter": "Capítulo 4: Relacionamentos",
    "instruction_pt": "`ALTER TABLE` modifica uma tabela existente. Use `ADD COLUMN` para adicionar colunas, `DROP COLUMN` para remover.\n\n  ALTER TABLE clientes ADD COLUMN telefone VARCHAR(15);\n\nEscreva o comando que adiciona a coluna `telefone` (VARCHAR 15) à tabela `usuarios`.",
    "instruction_en": "`ALTER TABLE` modifies an existing table. Use `ADD COLUMN` to add columns.",
    "instruction_es": "`ALTER TABLE` modifica una tabla existente. Usa `ADD COLUMN` para agregar columnas.",
    "starter_code": "-- Adicione a coluna telefone (VARCHAR(15)) à tabela usuarios\n-- escreva aqui\n",
    "hint": "ALTER TABLE usuarios ADD COLUMN telefone VARCHAR(15);",
    "tests": [{"stdin": "", "expected_stdout": "ALTER TABLE usuarios ADD COLUMN telefone VARCHAR(15);"}],
  },
],

# ── TypeScript ───────────────────────────────────────────────────────────────
"typescript": [
  {
    "order": 1,
    "title": "Tipos básicos",
    "chapter": "Capítulo 1: Tipagem Estática",
    "instruction_pt": "TypeScript adiciona tipos ao JavaScript. `let nome: string` garante que a variável só aceita texto. Escreva a declaração de uma variável `nome` do tipo `string` sem valor inicial.",
    "instruction_en": "TypeScript adds types to JavaScript. Write the declaration of a `nome` variable of type `string` with no initial value.",
    "instruction_es": "TypeScript añade tipos a JavaScript. Escribe la declaración de una variable `nome` de tipo `string` sin valor inicial.",
    "starter_code": '// Declare a variável "nome" com tipo string (sem valor inicial)\n// escreva aqui\n',
    "hint": "Sintaxe: let nome: string;",
    "tests": [{"stdin": "", "expected_stdout": "let nome: string;"}],
  },
  {
    "order": 2,
    "title": "Função tipada",
    "chapter": "Capítulo 1: Tipagem Estática",
    "instruction_pt": "Em TypeScript, funções têm tipos nos parâmetros e no retorno: `function nome(a: tipo): tipoRetorno`. Escreva a assinatura de uma função `somar` que recebe dois `number` e retorna `number`.",
    "instruction_en": "In TypeScript, functions have typed parameters and return types. Write the signature of a `somar` function that takes two `number` and returns `number`.",
    "instruction_es": "En TypeScript, las funciones tienen tipos en los parámetros y en el retorno.",
    "starter_code": '// Escreva a assinatura (apenas a primeira linha) da função somar\n// function somar(??): ?? {\n// escreva aqui\n',
    "hint": "function somar(a: number, b: number): number {",
    "tests": [{"stdin": "", "expected_stdout": "function somar(a: number, b: number): number {"}],
  },
  {
    "order": 3,
    "title": "Interface",
    "chapter": "Capítulo 2: Tipos Avançados",
    "instruction_pt": "Interfaces definem a forma de objetos. Escreva a interface `Aluno` com os campos `nome` (string) e `idade` (number) em uma linha, sem quebras de linha.",
    "instruction_en": "Interfaces define the shape of objects. Write the `Aluno` interface with fields `nome` (string) and `idade` (number) on one line.",
    "instruction_es": "Las interfaces definen la forma de los objetos. Escribe la interfaz `Aluno` con los campos `nome` (string) y `idade` (number) en una línea.",
    "starter_code": '// Escreva a interface Aluno com nome: string e idade: number\n// Formato: interface Aluno { nome: string; idade: number; }\n// escreva aqui\n',
    "hint": "interface NomeInterface { campo: tipo; campo2: tipo; }",
    "tests": [{"stdin": "", "expected_stdout": "interface Aluno { nome: string; idade: number; }"}],
  },
  {
    "order": 4,
    "title": "Type Alias",
    "chapter": "Capítulo 2: Tipos Avançados",
    "instruction_pt": "`type` cria um apelido para um tipo. Útil para reutilização. Escreva o type alias `Cor` que aceita os valores literais `'vermelho'`, `'azul'` ou `'verde'`.",
    "instruction_en": "`type` creates an alias for a type. Write the type alias `Cor` that accepts the literal values `'vermelho'`, `'azul'` or `'verde'`.",
    "instruction_es": "`type` crea un alias para un tipo. Escribe el type alias `Cor` que acepta los valores literales `'vermelho'`, `'azul'` o `'verde'`.",
    "starter_code": "// Escreva o type alias Cor com os três valores literais\n// type Cor = 'vermelho' | 'azul' | 'verde';\n// escreva aqui\n",
    "hint": "type NomeAlias = 'valor1' | 'valor2' | 'valor3'; — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": "type Cor = 'vermelho' | 'azul' | 'verde';"}],
  },
  {
    "order": 5,
    "title": "Union Types",
    "chapter": "Capítulo 2: Tipos Avançados",
    "instruction_pt": "Union types permitem que uma variável aceite mais de um tipo. Use `|` para combinar tipos. Declare a variável `id` que pode ser `number` ou `string`.",
    "instruction_en": "Union types allow a variable to accept more than one type. Use `|` to combine types. Declare the variable `id` that can be `number` or `string`.",
    "instruction_es": "Los union types permiten que una variable acepte más de un tipo. Declara la variable `id` que puede ser `number` o `string`.",
    "starter_code": "// Declare a variável id que aceita number OU string\n// escreva aqui\n",
    "hint": "let variavel: tipo1 | tipo2;",
    "tests": [{"stdin": "", "expected_stdout": "let id: number | string;"}],
  },
  {
    "order": 6,
    "title": "Arrays Tipados",
    "chapter": "Capítulo 3: Coleções",
    "instruction_pt": "Em TypeScript, arrays têm tipos: `number[]` é um array de números. Declare a variável `numeros` como um array de `number` com os valores `[1, 2, 3]`.",
    "instruction_en": "In TypeScript, arrays have types: `number[]` is an array of numbers. Declare the variable `numeros` as an array of `number` with values `[1, 2, 3]`.",
    "instruction_es": "En TypeScript, los arrays tienen tipos. Declara la variable `numeros` como un array de `number` con los valores `[1, 2, 3]`.",
    "starter_code": "// Declare o array numeros do tipo number[] com valores [1, 2, 3]\n// escreva aqui\n",
    "hint": "let variavel: tipo[] = [valor1, valor2, valor3];",
    "tests": [{"stdin": "", "expected_stdout": "let numeros: number[] = [1, 2, 3];"}],
  },
  {
    "order": 7,
    "title": "Propriedade Opcional",
    "chapter": "Capítulo 3: Coleções",
    "instruction_pt": "Em interfaces, adicione `?` após o nome do campo para torná-lo opcional. Escreva a interface `Config` com a propriedade opcional `debug` do tipo `boolean`.",
    "instruction_en": "In interfaces, add `?` after the field name to make it optional. Write the `Config` interface with an optional `debug` property of type `boolean`.",
    "instruction_es": "En las interfaces, añade `?` después del nombre del campo para hacerlo opcional. Escribe la interfaz `Config` con la propiedad opcional `debug` de tipo `boolean`.",
    "starter_code": "// Escreva a interface Config com a propriedade opcional debug: boolean\n// interface Config { debug?: boolean; }\n// escreva aqui\n",
    "hint": "interface NomeInterface { campo?: tipo; }",
    "tests": [{"stdin": "", "expected_stdout": "interface Config { debug?: boolean; }"}],
  },
  {
    "order": 8,
    "title": "Enum",
    "chapter": "Capítulo 4: Recursos Avançados",
    "instruction_pt": "`enum` define um conjunto nomeado de constantes. Escreva o enum `Direcao` com os membros `Norte`, `Sul`, `Leste` e `Oeste` em uma linha.",
    "instruction_en": "`enum` defines a named set of constants. Write the `Direcao` enum with members `Norte`, `Sul`, `Leste` and `Oeste` on one line.",
    "instruction_es": "`enum` define un conjunto nombrado de constantes. Escribe el enum `Direcao` con los miembros `Norte`, `Sul`, `Leste` y `Oeste` en una línea.",
    "starter_code": "// Escreva o enum Direcao com os 4 membros em uma linha\n// enum Direcao { Norte, Sul, Leste, Oeste }\n// escreva aqui\n",
    "hint": "enum NomeEnum { Membro1, Membro2, Membro3, Membro4 }",
    "tests": [{"stdin": "", "expected_stdout": "enum Direcao { Norte, Sul, Leste, Oeste }"}],
  },
  {
    "order": 9,
    "title": "Generics",
    "chapter": "Capítulo 4: Recursos Avançados",
    "instruction_pt": "Generics permitem criar funções e classes reutilizáveis para qualquer tipo. Escreva a assinatura da função genérica `identidade` que recebe um parâmetro `valor` do tipo `T` e retorna `T`.",
    "instruction_en": "Generics allow creating reusable functions for any type. Write the signature of the generic function `identidade` that receives a parameter `valor` of type `T` and returns `T`.",
    "instruction_es": "Los generics permiten crear funciones reutilizables para cualquier tipo. Escribe la firma de la función genérica `identidade`.",
    "starter_code": "// Escreva a assinatura da função genérica identidade<T>\n// function identidade<T>(valor: T): T {\n// escreva aqui\n",
    "hint": "function nomeFuncao<T>(param: T): T {",
    "tests": [{"stdin": "", "expected_stdout": "function identidade<T>(valor: T): T {"}],
  },
  {
    "order": 10,
    "title": "Classe Tipada",
    "chapter": "Capítulo 4: Recursos Avançados",
    "instruction_pt": "Classes em TypeScript podem ter propriedades tipadas no construtor usando `public`. Escreva a linha `constructor` da classe `Animal` com a propriedade pública `nome: string`.",
    "instruction_en": "TypeScript classes can have typed properties in the constructor using `public`. Write the `constructor` line of the `Animal` class with the public property `nome: string`.",
    "instruction_es": "Las clases TypeScript pueden tener propiedades tipadas en el constructor con `public`. Escribe la línea `constructor` de la clase `Animal`.",
    "starter_code": "// Escreva o constructor da classe Animal com a propriedade public nome: string\n// constructor(public nome: string) {}\n// escreva aqui\n",
    "hint": "constructor(public nomeProp: tipo) {}",
    "tests": [{"stdin": "", "expected_stdout": "constructor(public nome: string) {}"}],
  },
],

# ── Java ─────────────────────────────────────────────────────────────────────
"java": [
  {
    "order": 1,
    "title": "Imprimir no console",
    "chapter": "Capítulo 1: Fundamentos Java",
    "instruction_pt": "Java usa `System.out.println()` para imprimir no console. Escreva apenas o comando que imprime 'Olá, Java!'.",
    "instruction_en": "Java uses `System.out.println()` to print to the console. Write only the command that prints 'Olá, Java!'.",
    "instruction_es": "Java usa `System.out.println()` para imprimir en la consola. Escribe solo el comando que imprime 'Olá, Java!'.",
    "starter_code": 'public class Main {\n    public static void main(String[] args) {\n        // Escreva o comando para imprimir "Olá, Java!"\n        // escreva aqui\n    }\n}\n',
    "hint": "System.out.println(\"Olá, Java!\"); — aspas simples ' ou duplas \" são aceitas neste exercício.",
    "tests": [{"stdin": "", "expected_stdout": 'System.out.println("Olá, Java!");'}],
  },
  {
    "order": 2,
    "title": "Declarando variáveis",
    "chapter": "Capítulo 1: Fundamentos Java",
    "instruction_pt": "Java é fortemente tipado — toda variável precisa de um tipo. `int` para inteiros, `String` para texto. Escreva a declaração de um inteiro `idade` com valor 25.",
    "instruction_en": "Java is strongly typed — every variable needs a type. Write the declaration of an integer `idade` with value 25.",
    "instruction_es": "Java es fuertemente tipado. Escribe la declaración de un entero `idade` con valor 25.",
    "starter_code": '// Declare um inteiro chamado "idade" com valor 25\n// escreva aqui\n',
    "hint": "int nomeDaVariavel = valor;",
    "tests": [{"stdin": "", "expected_stdout": "int idade = 25;"}],
  },
  {
    "order": 3,
    "title": "Método estático",
    "chapter": "Capítulo 2: Orientação a Objetos",
    "instruction_pt": "Métodos em Java são declarados com `public static TipoRetorno nomeMetodo(Tipo param)`. Escreva a assinatura do método `dobrar` que recebe e retorna `int`.",
    "instruction_en": "Methods in Java are declared with `public static ReturnType methodName(Type param)`. Write the signature of the `dobrar` method that receives and returns `int`.",
    "instruction_es": "Los métodos en Java se declaran con `public static TipoRetorno nombreMetodo(Tipo param)`. Escribe la firma del método `dobrar`.",
    "starter_code": '// Escreva apenas a assinatura do método dobrar (sem o corpo)\n// Recebe int n e retorna int\n// escreva aqui\n',
    "hint": "public static int dobrar(int n) {",
    "tests": [{"stdin": "", "expected_stdout": "public static int dobrar(int n) {"}],
  },
  {
    "order": 4,
    "title": "Arrays",
    "chapter": "Capítulo 2: Orientação a Objetos",
    "instruction_pt": "Arrays em Java têm tamanho fixo e tipo declarado. Escreva a declaração do array `numeros` do tipo `int[]` com os valores `{1, 2, 3}` em uma linha.",
    "instruction_en": "Arrays in Java have a fixed size and a declared type. Write the declaration of the `numeros` array of type `int[]` with values `{1, 2, 3}` on one line.",
    "instruction_es": "Los arrays en Java tienen tamaño fijo y tipo declarado. Escribe la declaración del array `numeros` de tipo `int[]` con los valores `{1, 2, 3}`.",
    "starter_code": "// Declare o array de inteiros chamado numeros com {1, 2, 3}\n// int[] numeros = {1, 2, 3};\n// escreva aqui\n",
    "hint": "int[] nomeArray = {val1, val2, val3};",
    "tests": [{"stdin": "", "expected_stdout": "int[] numeros = {1, 2, 3};"}],
  },
  {
    "order": 5,
    "title": "Condicionais",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "Java usa `if (condição) { ... } else { ... }` para tomar decisões. Escreva a estrutura `if` que verifica se a variável `x` é maior que zero e imprime `'positivo'`.",
    "instruction_en": "Java uses `if (condition) { ... } else { ... }` to make decisions. Write the `if` structure that checks if variable `x` is greater than zero and prints `'positivo'`.",
    "instruction_es": "Java usa `if (condición) { ... } else { ... }` para tomar decisiones. Escribe la estructura `if` que verifica si la variable `x` es mayor que cero.",
    "starter_code": "// Escreva o bloco if que verifica x > 0 e imprime positivo\n// if (x > 0) {\n// escreva aqui\n",
    "hint": "if (variavel > 0) {",
    "tests": [{"stdin": "", "expected_stdout": "if (x > 0) {"}],
  },
  {
    "order": 6,
    "title": "Loop For",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "O `for` em Java tem três partes: inicialização, condição e incremento. Escreva o cabeçalho do `for` que conta de 0 até 4 (i < 5).",
    "instruction_en": "The `for` in Java has three parts: initialization, condition, and increment. Write the header of the `for` that counts from 0 to 4 (i < 5).",
    "instruction_es": "El `for` en Java tiene tres partes: inicialización, condición e incremento. Escribe el encabezado del `for` que cuenta de 0 a 4.",
    "starter_code": "// Escreva o cabeçalho do for que vai de 0 a 4\n// for (int i = 0; i < 5; i++) {\n// escreva aqui\n",
    "hint": "for (int i = 0; i < 5; i++) {",
    "tests": [{"stdin": "", "expected_stdout": "for (int i = 0; i < 5; i++) {"}],
  },
  {
    "order": 7,
    "title": "String em Java",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "`String` em Java é uma classe. Use o método `.length()` para obter o número de caracteres. Escreva a linha que declara a `String` chamada `msg` com o valor `'Olá'` e em seguida chama `msg.length()`.",
    "instruction_en": "`String` in Java is a class. Use the `.length()` method to get the number of characters. Write the declaration of the `String` `msg` with value `'Olá'`.",
    "instruction_es": "`String` en Java es una clase. Escribe la declaración de la `String` llamada `msg` con el valor `'Olá'`.",
    "starter_code": "// Declare a String msg com valor 'Olá'\n// String msg = \"Olá\";\n// escreva aqui\n",
    "hint": "String nomeDaVariavel = \"valor\"; — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": 'String msg = "Olá";'}],
  },
  {
    "order": 8,
    "title": "ArrayList",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "`ArrayList` é uma lista dinâmica em Java. Use `ArrayList<Tipo> nome = new ArrayList<>();` para criar uma. Escreva a declaração de um ArrayList de String chamado `nomes`.",
    "instruction_en": "`ArrayList` is a dynamic list in Java. Write the declaration of an ArrayList of String named `nomes`.",
    "instruction_es": "`ArrayList` es una lista dinámica en Java. Escribe la declaración de un ArrayList de String llamado `nomes`.",
    "starter_code": "// Declare um ArrayList de String chamado nomes\n// ArrayList<String> nomes = new ArrayList<>();\n// escreva aqui\n",
    "hint": "ArrayList<Tipo> nomeDaLista = new ArrayList<>();",
    "tests": [{"stdin": "", "expected_stdout": "ArrayList<String> nomes = new ArrayList<>();"}],
  },
  {
    "order": 9,
    "title": "Classe com Construtor",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "Uma classe em Java agrupa dados e comportamentos. Escreva a assinatura do construtor da classe `Pessoa` que recebe o parâmetro `String nome` e atribui `this.nome = nome`.",
    "instruction_en": "A class in Java groups data and behavior. Write the constructor signature of the `Pessoa` class that receives `String nome` and assigns `this.nome = nome`.",
    "instruction_es": "Una clase en Java agrupa datos y comportamientos. Escribe la firma del constructor de la clase `Pessoa`.",
    "starter_code": "// Escreva o construtor de Pessoa que recebe String nome\n// Pessoa(String nome) {\n// escreva aqui\n",
    "hint": "NomeDaClasse(Tipo parametro) {",
    "tests": [{"stdin": "", "expected_stdout": "Pessoa(String nome) {"}],
  },
  {
    "order": 10,
    "title": "Herança",
    "chapter": "Capítulo 5: Herança",
    "instruction_pt": "Herança em Java usa a palavra-chave `extends`. A subclasse herda todos os métodos e atributos da superclasse. Escreva a declaração da classe `Aluno` que herda de `Pessoa`.",
    "instruction_en": "Inheritance in Java uses the keyword `extends`. Write the declaration of the class `Aluno` that extends `Pessoa`.",
    "instruction_es": "La herencia en Java usa la palabra clave `extends`. Escribe la declaración de la clase `Aluno` que hereda de `Pessoa`.",
    "starter_code": "// Escreva a declaração da classe Aluno que herda de Pessoa\n// public class Aluno extends Pessoa {\n// escreva aqui\n",
    "hint": "public class SubClasse extends SuperClasse {",
    "tests": [{"stdin": "", "expected_stdout": "public class Aluno extends Pessoa {"}],
  },
],

# ── C++ ──────────────────────────────────────────────────────────────────────
"cpp": [
  {
    "order": 1,
    "title": "Saída no console",
    "chapter": "Capítulo 1: Fundamentos C++",
    "instruction_pt": "C++ usa `cout << \"texto\" << endl;` para exibir texto. `endl` quebra a linha. Escreva o comando que exibe 'Olá, C++!'.",
    "instruction_en": "C++ uses `cout << \"text\" << endl;` to display text. Write the command that displays 'Olá, C++!'.",
    "instruction_es": "C++ usa `cout << \"texto\" << endl;` para mostrar texto. Escribe el comando que muestra 'Olá, C++!'.",
    "starter_code": '#include <iostream>\nusing namespace std;\nint main() {\n    // Escreva o comando para exibir "Olá, C++!"\n    // escreva aqui\n    return 0;\n}\n',
    "hint": "cout << \"Olá, C++!\" << endl; — aspas simples ' ou duplas \" são aceitas neste exercício.",
    "tests": [{"stdin": "", "expected_stdout": 'cout << "Olá, C++!" << endl;'}],
  },
  {
    "order": 2,
    "title": "Declarando variáveis",
    "chapter": "Capítulo 1: Fundamentos C++",
    "instruction_pt": "C++ exige declaração de tipo: `int`, `double`, `string`. Escreva a declaração de um inteiro `nota` com valor 10.",
    "instruction_en": "C++ requires type declaration: `int`, `double`, `string`. Write the declaration of an integer `nota` with value 10.",
    "instruction_es": "C++ requiere declaración de tipo. Escribe la declaración de un entero `nota` con valor 10.",
    "starter_code": '// Declare um inteiro chamado "nota" com valor 10\n// escreva aqui\n',
    "hint": "int nomeDaVariavel = valor;",
    "tests": [{"stdin": "", "expected_stdout": "int nota = 10;"}],
  },
  {
    "order": 3,
    "title": "Função",
    "chapter": "Capítulo 2: Funções",
    "instruction_pt": "Funções C++ têm tipo de retorno antes do nome: `int soma(int a, int b)`. Escreva a assinatura da função `soma` que recebe dois inteiros e retorna inteiro.",
    "instruction_en": "C++ functions have return type before the name: `int soma(int a, int b)`. Write the signature of the `soma` function.",
    "instruction_es": "Las funciones C++ tienen el tipo de retorno antes del nombre. Escribe la firma de la función `soma`.",
    "starter_code": '// Escreva apenas a assinatura da função soma(int a, int b) que retorna int\n// escreva aqui\n',
    "hint": "int nomeFuncao(int a, int b) {",
    "tests": [{"stdin": "", "expected_stdout": "int soma(int a, int b) {"}],
  },
  {
    "order": 4,
    "title": "Arrays",
    "chapter": "Capítulo 2: Funções",
    "instruction_pt": "Arrays em C++ têm tamanho fixo. Declare o array de inteiros `numeros` com os valores `{1, 2, 3}` em uma linha.",
    "instruction_en": "Arrays in C++ have a fixed size. Declare the integer array `numeros` with values `{1, 2, 3}` on one line.",
    "instruction_es": "Los arrays en C++ tienen tamaño fijo. Declara el array de enteros `numeros` con los valores `{1, 2, 3}`.",
    "starter_code": "// Declare o array de inteiros numeros com {1, 2, 3}\n// int numeros[] = {1, 2, 3};\n// escreva aqui\n",
    "hint": "int nomeArray[] = {val1, val2, val3};",
    "tests": [{"stdin": "", "expected_stdout": "int numeros[] = {1, 2, 3};"}],
  },
  {
    "order": 5,
    "title": "Condicionais",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "C++ usa `if (condição) { ... } else { ... }`. Escreva o cabeçalho do `if` que verifica se a variável `x` é maior que zero.",
    "instruction_en": "C++ uses `if (condition) { ... } else { ... }`. Write the `if` header that checks if variable `x` is greater than zero.",
    "instruction_es": "C++ usa `if (condición) { ... }`. Escribe el encabezado del `if` que verifica si la variable `x` es mayor que cero.",
    "starter_code": "// Escreva o cabeçalho do if que verifica x > 0\n// if (x > 0) {\n// escreva aqui\n",
    "hint": "if (variavel > 0) {",
    "tests": [{"stdin": "", "expected_stdout": "if (x > 0) {"}],
  },
  {
    "order": 6,
    "title": "Loop For",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "O `for` em C++ funciona igual ao Java: inicialização, condição e incremento. Escreva o cabeçalho do `for` que conta de 0 até 4 (i < 5).",
    "instruction_en": "The `for` in C++ works the same as Java. Write the header of the `for` that counts from 0 to 4 (i < 5).",
    "instruction_es": "El `for` en C++ funciona igual que en Java. Escribe el encabezado del `for` que cuenta de 0 a 4.",
    "starter_code": "// Escreva o cabeçalho do for que vai de 0 a 4\n// for (int i = 0; i < 5; i++) {\n// escreva aqui\n",
    "hint": "for (int i = 0; i < 5; i++) {",
    "tests": [{"stdin": "", "expected_stdout": "for (int i = 0; i < 5; i++) {"}],
  },
  {
    "order": 7,
    "title": "String em C++",
    "chapter": "Capítulo 3: Controle de Fluxo",
    "instruction_pt": "C++ tem o tipo `string` (da biblioteca `<string>`). Declare a variável `nome` do tipo `string` com o valor `'Carlos'`.",
    "instruction_en": "C++ has the `string` type (from the `<string>` library). Declare the variable `nome` of type `string` with the value `'Carlos'`.",
    "instruction_es": "C++ tiene el tipo `string`. Declara la variable `nome` de tipo `string` con el valor `'Carlos'`.",
    "starter_code": "// Declare a string nome com valor Carlos\n// string nome = \"Carlos\";\n// escreva aqui\n",
    "hint": "string nomeDaVariavel = \"valor\"; — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": 'string nome = "Carlos";'}],
  },
  {
    "order": 8,
    "title": "Vector",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "`vector` é a coleção dinâmica de C++ (da `<vector>`). Escreva a declaração do vector de inteiros `numeros` com os valores `{1, 2, 3}`.",
    "instruction_en": "`vector` is C++'s dynamic collection. Write the declaration of the integer vector `numeros` with values `{1, 2, 3}`.",
    "instruction_es": "`vector` es la colección dinámica de C++. Escribe la declaración del vector de enteros `numeros` con los valores `{1, 2, 3}`.",
    "starter_code": "// Declare o vector<int> chamado numeros com {1, 2, 3}\n// vector<int> numeros = {1, 2, 3};\n// escreva aqui\n",
    "hint": "vector<Tipo> nomeVector = {val1, val2, val3};",
    "tests": [{"stdin": "", "expected_stdout": "vector<int> numeros = {1, 2, 3};"}],
  },
  {
    "order": 9,
    "title": "Struct",
    "chapter": "Capítulo 4: Coleções",
    "instruction_pt": "`struct` em C++ agrupa variáveis relacionadas. Escreva a declaração da struct `Pessoa` com os campos `string nome` e `int idade` em uma linha.",
    "instruction_en": "`struct` in C++ groups related variables. Write the declaration of the struct `Pessoa` with fields `string nome` and `int idade` on one line.",
    "instruction_es": "`struct` en C++ agrupa variables relacionadas. Escribe la declaración de la struct `Pessoa` con los campos `string nome` e `int idade`.",
    "starter_code": "// Escreva a struct Pessoa com nome e idade em uma linha\n// struct Pessoa { string nome; int idade; };\n// escreva aqui\n",
    "hint": "struct NomeDaStruct { tipo campo1; tipo campo2; };",
    "tests": [{"stdin": "", "expected_stdout": "struct Pessoa { string nome; int idade; };"}],
  },
  {
    "order": 10,
    "title": "Ponteiros",
    "chapter": "Capítulo 5: Ponteiros",
    "instruction_pt": "Ponteiros armazenam o endereço de memória de uma variável. `int* ptr = &x;` cria um ponteiro que aponta para `x`. Escreva essa declaração de ponteiro para a variável inteira `x`.",
    "instruction_en": "Pointers store the memory address of a variable. `int* ptr = &x;` creates a pointer pointing to `x`. Write that pointer declaration.",
    "instruction_es": "Los punteros almacenan la dirección de memoria de una variable. Escribe la declaración del puntero `ptr` que apunta a `x`.",
    "starter_code": "// Declare um ponteiro ptr que aponta para a variável inteira x\n// int* ptr = &x;\n// escreva aqui\n",
    "hint": "tipo* nomePonteiro = &nomeVariavel;",
    "tests": [{"stdin": "", "expected_stdout": "int* ptr = &x;"}],
  },
],

# ── Go ───────────────────────────────────────────────────────────────────────
"go": [
  {
    "order": 1,
    "title": "fmt.Println",
    "chapter": "Capítulo 1: Introdução ao Go",
    "instruction_pt": "Go usa `fmt.Println()` para exibir texto com quebra de linha. Escreva o comando que exibe 'Olá, Go!'.",
    "instruction_en": "Go uses `fmt.Println()` to display text with a newline. Write the command that displays 'Olá, Go!'.",
    "instruction_es": "Go usa `fmt.Println()` para mostrar texto con salto de línea. Escribe el comando que muestra 'Olá, Go!'.",
    "starter_code": 'package main\nimport "fmt"\nfunc main() {\n    // Exiba "Olá, Go!"\n    // escreva aqui\n}\n',
    "hint": "fmt.Println(\"Olá, Go!\") — aspas simples ' ou duplas \" são aceitas neste exercício.",
    "tests": [{"stdin": "", "expected_stdout": 'fmt.Println("Olá, Go!")'}],
  },
  {
    "order": 2,
    "title": "Declaração curta",
    "chapter": "Capítulo 1: Introdução ao Go",
    "instruction_pt": "Go permite declarar variáveis com `:=` — o compilador infere o tipo automaticamente. Escreva a declaração da variável `nome` com valor 'Gopher'.",
    "instruction_en": "Go allows declaring variables with `:=` — the compiler infers the type automatically. Write the declaration of variable `nome` with value 'Gopher'.",
    "instruction_es": "Go permite declarar variables con `:=` — el compilador infiere el tipo automáticamente.",
    "starter_code": '// Declare a variável "nome" com valor "Gopher" usando :=\n// escreva aqui\n',
    "hint": "nome := \"Gopher\" — aspas simples ' ou duplas \" são aceitas neste exercício.",
    "tests": [{"stdin": "", "expected_stdout": 'nome := "Gopher"'}],
  },
  {
    "order": 3,
    "title": "Função",
    "chapter": "Capítulo 2: Funções",
    "instruction_pt": "Go declara funções com `func nome(params tipo) tipoRetorno`. Escreva a assinatura da função `dobrar` que recebe `n int` e retorna `int`.",
    "instruction_en": "Go declares functions with `func name(params type) returnType`. Write the signature of `dobrar` function.",
    "instruction_es": "Go declara funciones con `func nombre(params tipo) tipoRetorno`. Escribe la firma de la función `dobrar`.",
    "starter_code": '// Escreva a assinatura da função dobrar(n int) que retorna int\n// escreva aqui\n',
    "hint": "func dobrar(n int) int {",
    "tests": [{"stdin": "", "expected_stdout": "func dobrar(n int) int {"}],
  },
  {
    "order": 4,
    "title": "Slices",
    "chapter": "Capítulo 2: Funções",
    "instruction_pt": "Slices são arrays dinâmicos em Go. Declare o slice de inteiros `numeros` com os valores `{1, 2, 3}` usando a sintaxe literal.",
    "instruction_en": "Slices are dynamic arrays in Go. Declare the integer slice `numeros` with values `{1, 2, 3}` using literal syntax.",
    "instruction_es": "Los slices son arrays dinámicos en Go. Declara el slice de enteros `numeros` con los valores `{1, 2, 3}`.",
    "starter_code": "// Declare o slice de int chamado numeros com {1, 2, 3}\n// numeros := []int{1, 2, 3}\n// escreva aqui\n",
    "hint": "nomeSlice := []tipo{val1, val2, val3}",
    "tests": [{"stdin": "", "expected_stdout": "numeros := []int{1, 2, 3}"}],
  },
  {
    "order": 5,
    "title": "Maps",
    "chapter": "Capítulo 3: Coleções",
    "instruction_pt": "Maps são dicionários em Go. Escreva a declaração do map `idades` que mapeia `string` para `int`, com um par `'Ana': 20` usando sintaxe literal.",
    "instruction_en": "Maps are dictionaries in Go. Write the declaration of the `idades` map that maps `string` to `int`, with one pair `'Ana': 20` using literal syntax.",
    "instruction_es": "Los maps son diccionarios en Go. Escribe la declaración del map `idades` que mapea `string` a `int`, con el par `'Ana': 20`.",
    "starter_code": "// Declare o map idades com um par Ana:20\n// idades := map[string]int{\"Ana\": 20}\n// escreva aqui\n",
    "hint": "nomeMap := map[tipoChave]tipoValor{\"chave\": valor} — aspas simples ' ou duplas \" são aceitas.",
    "tests": [{"stdin": "", "expected_stdout": 'idades := map[string]int{"Ana": 20}'}],
  },
  {
    "order": 6,
    "title": "Condicionais",
    "chapter": "Capítulo 3: Coleções",
    "instruction_pt": "Go usa `if` sem parênteses ao redor da condição. Escreva o cabeçalho do `if` que verifica se a variável `x` é maior que zero.",
    "instruction_en": "Go uses `if` without parentheses around the condition. Write the `if` header that checks if variable `x` is greater than zero.",
    "instruction_es": "Go usa `if` sin paréntesis alrededor de la condición. Escribe el encabezado del `if` que verifica si `x` es mayor que cero.",
    "starter_code": "// Escreva o cabeçalho do if que verifica x > 0 (sem parênteses)\n// if x > 0 {\n// escreva aqui\n",
    "hint": "if variavel > 0 {",
    "tests": [{"stdin": "", "expected_stdout": "if x > 0 {"}],
  },
  {
    "order": 7,
    "title": "Loop For",
    "chapter": "Capítulo 3: Coleções",
    "instruction_pt": "Go tem apenas `for` como estrutura de repetição (sem `while`). Escreva o cabeçalho do `for` que conta de 0 até 4 (i < 5).",
    "instruction_en": "Go has only `for` as a loop construct (no `while`). Write the header of the `for` that counts from 0 to 4 (i < 5).",
    "instruction_es": "Go solo tiene `for` como estructura de repetición. Escribe el encabezado del `for` que cuenta de 0 a 4.",
    "starter_code": "// Escreva o cabeçalho do for que vai de 0 a 4 (sem parênteses)\n// for i := 0; i < 5; i++ {\n// escreva aqui\n",
    "hint": "for i := 0; i < 5; i++ {",
    "tests": [{"stdin": "", "expected_stdout": "for i := 0; i < 5; i++ {"}],
  },
  {
    "order": 8,
    "title": "Struct",
    "chapter": "Capítulo 4: Tipos e Structs",
    "instruction_pt": "`struct` em Go agrupa campos relacionados. Use `type NomeStruct struct { ... }`. Escreva a struct `Pessoa` com os campos `Nome string` e `Idade int` em uma linha.",
    "instruction_en": "`struct` in Go groups related fields. Write the `Pessoa` struct with fields `Nome string` and `Idade int` on one line.",
    "instruction_es": "`struct` en Go agrupa campos relacionados. Escribe la struct `Pessoa` con los campos `Nome string` e `Idade int` en una línea.",
    "starter_code": "// Escreva a struct Pessoa com Nome string e Idade int em uma linha\n// type Pessoa struct { Nome string; Idade int }\n// escreva aqui\n",
    "hint": "type NomeDaStruct struct { Campo1 tipo1; Campo2 tipo2 }",
    "tests": [{"stdin": "", "expected_stdout": "type Pessoa struct { Nome string; Idade int }"}],
  },
  {
    "order": 9,
    "title": "Métodos em Struct",
    "chapter": "Capítulo 4: Tipos e Structs",
    "instruction_pt": "Go adiciona métodos a structs com um *receiver*. Escreva a assinatura do método `saudar` que pertence a `Pessoa` e retorna `string`.",
    "instruction_en": "Go adds methods to structs with a *receiver*. Write the signature of the `saudar` method that belongs to `Pessoa` and returns `string`.",
    "instruction_es": "Go añade métodos a structs con un *receiver*. Escribe la firma del método `saudar` que pertenece a `Pessoa` y retorna `string`.",
    "starter_code": "// Escreva a assinatura do método saudar com receiver (p Pessoa) retornando string\n// func (p Pessoa) saudar() string {\n// escreva aqui\n",
    "hint": "func (receiver NomeStruct) nomeMetodo() tipoRetorno {",
    "tests": [{"stdin": "", "expected_stdout": "func (p Pessoa) saudar() string {"}],
  },
  {
    "order": 10,
    "title": "Interface",
    "chapter": "Capítulo 5: Interfaces",
    "instruction_pt": "Interfaces em Go definem comportamentos. Qualquer struct que implemente os métodos satisfaz a interface automaticamente. Escreva a interface `Animal` com o método `Falar() string` em uma linha.",
    "instruction_en": "Interfaces in Go define behaviors. Any struct that implements the methods satisfies the interface automatically. Write the `Animal` interface with the method `Falar() string` on one line.",
    "instruction_es": "Las interfaces en Go definen comportamientos. Escribe la interfaz `Animal` con el método `Falar() string` en una línea.",
    "starter_code": "// Escreva a interface Animal com o método Falar() string em uma linha\n// type Animal interface { Falar() string }\n// escreva aqui\n",
    "hint": "type NomeInterface interface { NomeMetodo() tipoRetorno }",
    "tests": [{"stdin": "", "expected_stdout": "type Animal interface { Falar() string }"}],
  },
],

# ── AI Prompts ───────────────────────────────────────────────────────────────
"ai-prompts": [
  {
    "order": 1,
    "title": "Comando Direto",
    "chapter": "Capítulo 1: Fundamentos de Prompting",
    "instruction_pt": "Um bom prompt é específico e contextualizado. Em vez de 'Me fale sobre Python', escreva um prompt que peça exatamente 3 exemplos de uso de Python para ciência de dados, em português.",
    "instruction_en": "A good prompt is specific and contextual. Instead of 'Tell me about Python', write a prompt that asks for exactly 3 Python use cases for data science.",
    "instruction_es": "Un buen prompt es específico y contextualizado. Escribe un prompt que pida exactamente 3 casos de uso de Python para ciencia de datos.",
    "starter_code": '// Escreva um prompt direto e específico:\n// Peça 3 exemplos de uso de Python para ciência de dados em português\n// escreva aqui\n',
    "hint": "Seja específico: quantidade, tema, formato, idioma.",
    "tests": [{"stdin": "", "expected_stdout": "Dê-me 3 exemplos de uso de Python para ciência de dados, em português."}],
  },
  {
    "order": 2,
    "title": "Atribuindo uma Persona",
    "chapter": "Capítulo 1: Fundamentos de Prompting",
    "instruction_pt": "Atribuir uma persona à IA muda a forma como ela responde. 'Aja como um professor de matemática do ensino médio' gera respostas pedagógicas. Escreva o prompt que pede à IA que atue como um tutor de programação paciente e explique o que é uma variável.",
    "instruction_en": "Assigning a persona changes how the AI responds. Write the prompt that asks the AI to act as a patient programming tutor and explain what a variable is.",
    "instruction_es": "Asignar una persona cambia cómo responde la IA. Escribe el prompt que le pide a la IA que actúe como un tutor de programación paciente.",
    "starter_code": '// Escreva um prompt com persona:\n// Peça à IA que aja como tutor de programação e explique variáveis\n// escreva aqui\n',
    "hint": "Estrutura: Aja como [persona]. [Tarefa].",
    "tests": [{"stdin": "", "expected_stdout": "Aja como um tutor de programação paciente. Explique o que é uma variável de forma simples."}],
  },
  {
    "order": 3,
    "title": "Cadeia de Pensamento",
    "chapter": "Capítulo 2: Técnicas Avançadas",
    "instruction_pt": "Chain-of-thought (cadeia de pensamento) melhora respostas pedindo que a IA raciocine passo a passo antes de responder. Escreva o prompt que pede à IA para resolver 'Quanto é 17 × 23?' pensando passo a passo.",
    "instruction_en": "Chain-of-thought improves responses by asking the AI to reason step by step. Write the prompt that asks the AI to solve '17 × 23' thinking step by step.",
    "instruction_es": "La cadena de pensamiento mejora las respuestas pidiendo a la IA que razone paso a paso.",
    "starter_code": '// Escreva um prompt chain-of-thought:\n// Peça à IA para resolver 17 × 23 pensando passo a passo\n// escreva aqui\n',
    "hint": "Adicione 'Pense passo a passo antes de responder.' ao final do prompt.",
    "tests": [{"stdin": "", "expected_stdout": "Quanto é 17 × 23? Pense passo a passo antes de responder."}],
  },
  {
    "order": 4,
    "title": "Few-Shot Prompting",
    "chapter": "Capítulo 2: Técnicas Avançadas",
    "instruction_pt": "Few-shot prompting fornece exemplos antes de pedir a tarefa. Escreva um prompt few-shot que ensine à IA o padrão 'Produto → Slogan' com dois exemplos e peça o slogan para 'Café'.",
    "instruction_en": "Few-shot prompting gives examples before asking the task. Write a few-shot prompt teaching the 'Product → Slogan' pattern with two examples and asking for a slogan for 'Coffee'.",
    "instruction_es": "Few-shot prompting proporciona ejemplos antes de pedir la tarea. Escribe un prompt few-shot que enseñe el patrón 'Producto → Slogan' con dos ejemplos.",
    "starter_code": "// Escreva um prompt few-shot com o padrão Produto → Slogan:\n// Dê dois exemplos e peça o slogan para Café\n// escreva aqui\n",
    "hint": "Estrutura: Produto: X → Slogan: Y. Produto: A → Slogan: B. Produto: Café → Slogan:",
    "tests": [{"stdin": "", "expected_stdout": "Produto: Tênis → Slogan: Vá além dos seus limites. Produto: Livro → Slogan: Abra um mundo novo. Produto: Café → Slogan:"}],
  },
  {
    "order": 5,
    "title": "Formato de Saída",
    "chapter": "Capítulo 2: Técnicas Avançadas",
    "instruction_pt": "Pedir um formato específico na saída torna a IA muito mais útil. Escreva um prompt que liste as 3 maiores linguagens de programação em formato JSON com os campos `nome` e `uso_principal`.",
    "instruction_en": "Asking for a specific output format makes the AI much more useful. Write a prompt that lists the top 3 programming languages in JSON format with fields `nome` and `uso_principal`.",
    "instruction_es": "Pedir un formato específico hace a la IA mucho más útil. Escribe un prompt que liste los 3 lenguajes de programación más usados en formato JSON.",
    "starter_code": "// Escreva um prompt que peça uma lista em JSON\n// com os campos nome e uso_principal\n// escreva aqui\n",
    "hint": "Liste as 3 linguagens de programação mais populares em JSON com os campos nome e uso_principal.",
    "tests": [{"stdin": "", "expected_stdout": "Liste as 3 linguagens de programação mais populares em formato JSON. Cada item deve ter os campos nome e uso_principal."}],
  },
  {
    "order": 6,
    "title": "Prompt para Código",
    "chapter": "Capítulo 3: Prompts para Desenvolvimento",
    "instruction_pt": "Prompts para gerar código precisam especificar linguagem, o que o código deve fazer e como deve ser estruturado. Escreva um prompt que peça uma função Python que receba uma lista de números e retorne a média, com docstring.",
    "instruction_en": "Prompts for code generation need to specify the language, what the code should do, and how it should be structured. Write a prompt asking for a Python function that takes a list of numbers and returns the average, with a docstring.",
    "instruction_es": "Los prompts para generar código deben especificar el lenguaje y la estructura. Escribe un prompt que pida una función Python que calcule la media de una lista.",
    "starter_code": "// Escreva um prompt para gerar uma função Python\n// que calcule a média de uma lista, com docstring\n// escreva aqui\n",
    "hint": "Escreva uma função Python chamada calcular_media que receba uma lista de números e retorne a média. Inclua docstring.",
    "tests": [{"stdin": "", "expected_stdout": "Escreva uma função Python chamada calcular_media que receba uma lista de números e retorne a média aritmética. Inclua docstring explicando os parâmetros e o retorno."}],
  },
  {
    "order": 7,
    "title": "Restrições no Prompt",
    "chapter": "Capítulo 3: Prompts para Desenvolvimento",
    "instruction_pt": "Adicionar restrições ao prompt aumenta a precisão da resposta. Escreva um prompt que explique o que é machine learning em no máximo 3 frases, sem jargões técnicos, para um aluno do ensino médio.",
    "instruction_en": "Adding constraints to the prompt increases the precision of the response. Write a prompt that explains what machine learning is in at most 3 sentences, without technical jargon, for a high school student.",
    "instruction_es": "Añadir restricciones al prompt aumenta la precisión. Escribe un prompt que explique qué es el machine learning en máximo 3 frases, sin jerga técnica.",
    "starter_code": "// Escreva um prompt com restrições:\n// - no máximo 3 frases\n// - sem jargões técnicos\n// - para aluno do ensino médio\n// escreva aqui\n",
    "hint": "Explique X em no máximo N frases, sem jargões, para [público-alvo].",
    "tests": [{"stdin": "", "expected_stdout": "Explique o que é machine learning em no máximo 3 frases, sem jargões técnicos, como se estivesse falando com um aluno do ensino médio."}],
  },
  {
    "order": 8,
    "title": "Projeto Final: Prompt Completo",
    "chapter": "Capítulo 4: Projeto Final",
    "instruction_pt": "Um prompt profissional combina: persona, contexto, tarefa, formato e restrições. Escreva um prompt completo pedindo à IA que aja como um coach de carreira, analise o perfil de um desenvolvedor júnior e dê 3 dicas de crescimento em formato de lista numerada.",
    "instruction_en": "A professional prompt combines: persona, context, task, format, and constraints. Write a complete prompt asking the AI to act as a career coach, analyze a junior developer's profile, and give 3 growth tips in a numbered list.",
    "instruction_es": "Un prompt profesional combina: persona, contexto, tarea, formato y restricciones. Escribe un prompt completo pidiendo a la IA que actúe como coach de carrera.",
    "starter_code": "// Escreva um prompt profissional completo com:\n// - persona (coach de carreira)\n// - tarefa (analisar perfil de dev júnior)\n// - formato (lista numerada com 3 dicas)\n// escreva aqui\n",
    "hint": "Aja como [persona]. [Contexto]. [Tarefa]. Formato: [especificação].",
    "tests": [{"stdin": "", "expected_stdout": "Aja como um coach de carreira experiente em tecnologia. Analise o perfil de um desenvolvedor júnior com 1 ano de experiência em Python. Dê 3 dicas práticas de crescimento profissional em formato de lista numerada."}],
  },
],

} # fim LESSONS

# ---------------------------------------------------------------------------
# Engine de inserção
# ---------------------------------------------------------------------------

def _slug_base(title: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")[:40]


def _build_doc(path_cfg: dict, les: dict) -> dict:
    order = les["order"]
    return {
        "id": str(uuid.uuid4()),
        "slug": f"{path_cfg['slug']}-{order:02d}-{_slug_base(les['title'])}",
        "path_slug": path_cfg["slug"],
        "order": order,
        "title": les["title"],
        "chapter": les.get("chapter", "Capítulo 1"),
        "instruction_pt": les.get("instruction_pt", ""),
        "instruction_en": les.get("instruction_en", ""),
        "instruction_es": les.get("instruction_es", ""),
        "starter_code": les.get("starter_code", ""),
        "hint": les.get("hint", ""),
        "tests": les.get("tests", []),
        "language": path_cfg["language"],
        "real_exec": path_cfg["real_exec"],
        "updated_at": datetime.utcnow().isoformat(),
    }


async def seed_path(path_cfg: dict):
    slug = path_cfg["slug"]
    lessons_data = LESSONS.get(slug, [])
    if not lessons_data:
        print(f"  aviso: nenhuma lição definida para {slug}")
        return

    # Upsert path metadata
    await db.paths.update_one(
        {"slug": slug},
        {"$set": {
            "slug": slug,
            "name": path_cfg["name"],
            "language": path_cfg["language"],
            "color": path_cfg["color"],
            "desc": path_cfg["desc"],
            "real_exec": path_cfg["real_exec"],
            "total_lessons": len(lessons_data),
            "updated_at": datetime.utcnow().isoformat(),
        }},
        upsert=True,
    )

    # Upsert each lesson
    for les in lessons_data:
        doc = _build_doc(path_cfg, les)
        await db.lessons.update_one(
            {"path_slug": slug, "order": doc["order"]},
            {"$set": doc},
            upsert=True,
        )

    print(f"  {path_cfg['name']}: {len(lessons_data)} lições inseridas")


async def main(slugs=None):
    await db.paths.create_index("slug", unique=True)
    await db.lessons.create_index([("path_slug", 1), ("order", 1)], unique=True)
    await db.lessons.create_index("slug", unique=True)

    targets = PATHS if not slugs else [p for p in PATHS if p["slug"] in slugs]
    print(f"Populando {len(targets)} trilha(s)...")
    for p in targets:
        await seed_path(p)
    print("Pronto!")


if __name__ == "__main__":
    asyncio.run(main(sys.argv[1:] or None))
